// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD0Pwm4O9NB1CR0HYHZv1e_d1fCxmWIFk',
    appId: '1:623976511544:web:3bfffb73d8952dc1710ecd',
    messagingSenderId: '623976511544',
    projectId: 'paemotion-99203',
    authDomain: 'paemotion-99203.firebaseapp.com',
    storageBucket: 'paemotion-99203.firebasestorage.app',
    measurementId: 'G-HQQ9JMX184',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZmEAVOxqipbIVE5DysnoIlcYXfwQT1nY',
    appId: '1:623976511544:android:ce0e0390612deac2710ecd',
    messagingSenderId: '623976511544',
    projectId: 'paemotion-99203',
    storageBucket: 'paemotion-99203.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxh5TdQ0qUHfT4_qQL21b5UlMJ8OnoWqU',
    appId: '1:623976511544:ios:703c8a57af2c757a710ecd',
    messagingSenderId: '623976511544',
    projectId: 'paemotion-99203',
    storageBucket: 'paemotion-99203.firebasestorage.app',
    iosBundleId: 'com.example.paemotion',
  );
}
